In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Setup successful!")

Setup successful!

# Assignment 1: Data Profiling

## Organisation and Business Question

An online fashion retailer wants to understand which customer demographic segments and product categories drive the highest return rates to optimize inventory management and reduce processing costs.

In [34]:
#import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [35]:
#load data
customers = pd.read_csv("data/customers.csv") 
products = pd.read_csv("data/products.csv")

transactions_preview = pd.read_csv(
    "data/transactions.csv",
    nrows=1000
)

C:\Users\Afiq Amali\AppData\Local\Temp\ipykernel_25716\2992051339.py:2: DtypeWarning: Columns (3: Telephone) have mixed types. Specify dtype option on import or set low_memory=False.
  customers = pd.read_csv("data/customers.csv")

In [36]:
customers.head()

,Customer ID,Name,Email,Telephone,City,Country,Gender,Date Of Birth,Job Title
0,1,Tyler Garcia,tyler.garcia@fake_gmail.com,922.970.2265x47563,New York,United States,M,2003-07-15,NaN
1,2,Joshua Miller,joshua.miller@fake_gmail.com,+1-958-729-6169,New York,United States,M,2000-06-16,Records manager
2,3,Alison Marshall DDS,alison.marshall.dds@fake_hotmail.com,+1-645-567-0876x5409,New York,United States,F,2003-07-22,NaN
3,4,Jeffery Acosta,jeffery.acosta@fake_yahoo.com,212.336.0912x84994,New York,United States,M,1996-11-12,Proofreader
4,5,Ashley Sanders,ashley.sanders@fake_hotmail.com,7814535781,New York,United States,F,1998-02-10,Exercise physiologist

In [37]:
products.head()

,Product ID,Category,Sub Category,Description PT,Description DE,Description FR,Description ES,Description EN,Description ZH,Color,Sizes,Production Cost
0,1,Feminine,Coats and Blazers,Esportivo Veludo Verde Com Botões,Sport Samt Sport Mit Knöpfen,Sports Velvet Sports Avec Des Boutons,Deportes De Terciopelo Con Botones,Sports Velvet Sports With Buttons,运动天鹅绒运动与按钮,NaN,S|M|L|XL,10.73
1,2,Feminine,Sweaters and Knitwear,Luxuoso Denim Rosa Com Botões,Luxuriöser Rosa Jeans Mit Knöpfen,Léchard De Denim Rose Avec Boutons,Denim Rosa Lujoso Con Botones,Luxurious Pink Denim With Buttons,豪华的粉红色牛仔布和纽扣,PINK,S|M|L|XL,19.55
2,3,Feminine,Dresses and Jumpsuits,Retrô Tricot Preto Estampado,Black Tricot Gedruckter Tricot,Tricot Imprimé En Tricot Noir,Tricot Negro Tricot Impreso,Black Tricot Printed Tricot,黑色三角形印刷三角形,BLACK,S|M|L|XL,25.59
3,4,Feminine,Shirts and Blouses,Blusa De Algodão Básica,Basis -Baumwollbluse,Chemisier En Coton De Base,Blusa De Algodón,Basic Cotton Blouse,基本的棉衬衫,NaN,S|M|L|XL,27.62
4,5,Feminine,T-shirts and Tops,T-Shirt Básica De Algodão,Basis-Baumwoll-T-Shirt,T-Shirt En Coton De Base,Camiseta Básica De Algodón,Basic Cotton T-Shirt,基本棉T恤,NaN,S|M|L,11.69

In [38]:
transactions_preview.head()

,Invoice ID,Line,Customer ID,Product ID,Size,Color,Unit Price,Quantity,Date,Discount,Line Total,Store ID,Employee ID,Currency,Currency Symbol,SKU,Transaction Type,Payment Method,Invoice Total
0,INV-US-001-03558761,1,47162,485,M,NaN,80.5,1,2023-01-01 15:42:00,0.0,80.5,1,7,USD,$,MASU485-M-,Sale,Cash,126.7
1,INV-US-001-03558761,2,47162,2779,G,NaN,31.5,1,2023-01-01 15:42:00,0.4,18.9,1,7,USD,$,CHCO2779-G-,Sale,Cash,126.7
2,INV-US-001-03558761,3,47162,64,M,NEUTRAL,45.5,1,2023-01-01 15:42:00,0.4,27.3,1,7,USD,$,MACO64-M-NEUTRAL,Sale,Cash,126.7
3,INV-US-001-03558762,1,10142,131,M,BLUE,70.0,1,2023-01-01 20:04:00,0.4,42.0,1,6,USD,$,FECO131-M-BLUE,Sale,Cash,77.0
4,INV-US-001-03558762,2,10142,716,L,WHITE,26.0,1,2023-01-01 20:04:00,0.0,26.0,1,6,USD,$,MAT-716-L-WHITE,Sale,Cash,77.0

### Customers table consist of 1643306 row and 9 column ###
### Products  table consist of 17940 row and 12 column ###
### Transaction preview table consist of 1000 row and 19 column ###
### (Note that Transaction preview row is 1000 because only 1000 data is load due to huge number of row in original dataset csv file) ###

In [39]:
print("Customers shape:", customers.shape)
print("Products shape:", products.shape)
print("Transaction preview shape:", transactions_preview.shape)

Customers shape: (1643306, 9)
Products shape: (17940, 12)
Transaction preview shape: (1000, 19)

### This code display all the column name for each dataset ###

In [40]:
print("Customer columns:")
print(customers.columns.tolist())

print("\nProduct columns:")
print(products.columns.tolist())

print("\nTransaction columns:")
print(transactions_preview.columns.tolist())

Customer columns:
['Customer ID', 'Name', 'Email', 'Telephone', 'City', 'Country', 'Gender', 'Date Of Birth', 'Job Title']

Product columns:
['Product ID', 'Category', 'Sub Category', 'Description PT', 'Description DE', 'Description FR', 'Description ES', 'Description EN', 'Description ZH', 'Color', 'Sizes', 'Production Cost']

Transaction columns:
['Invoice ID', 'Line', 'Customer ID', 'Product ID', 'Size', 'Color', 'Unit Price', 'Quantity', 'Date', 'Discount', 'Line Total', 'Store ID', 'Employee ID', 'Currency', 'Currency Symbol', 'SKU', 'Transaction Type', 'Payment Method', 'Invoice Total']

### This code display non-null count for every column for each dataset ###

In [41]:
print("CUSTOMERS")
customers.info()

print("\nPRODUCTS")
products.info()

print("\nTRANSACTIONS")
transactions_preview.info()

CUSTOMERS
<class 'pandas.DataFrame'>
RangeIndex: 1643306 entries, 0 to 1643305
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Customer ID    1643306 non-null  int64
 1   Name           1643306 non-null  str
 2   Email          1643306 non-null  str
 3   Telephone      1643306 non-null  object
 4   City           1643306 non-null  str
 5   Country        1643306 non-null  str
 6   Gender         1643306 non-null  str
 7   Date Of Birth  1643306 non-null  str
 8   Job Title      1059121 non-null  str
dtypes: int64(1), object(1), str(7)
memory usage: 112.8+ MB

PRODUCTS
<class 'pandas.DataFrame'>
RangeIndex: 17940 entries, 0 to 17939
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Product ID       17940 non-null  int64
 1   Category         17940 non-null  str
 2   Sub Category     17940 non-null  str
 3   Description PT   17940 non-null  str
 4   Description DE   17940 non-null  str
 5   Description FR   17940 non-null  str
 6   Description ES   17940 non-null  str
 7   Description EN   17940 non-null  str
 8   Description ZH   17940 non-null  str
 9   Color            5495 non-null   str
 10  Sizes            15870 non-null  str
 11  Production Cost  17940 non-null  float64
dtypes: float64(1), int64(1), str(10)
memory usage: 1.6 MB

TRANSACTIONS
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Invoice ID        1000 non-null   str
 1   Line              1000 non-null   int64
 2   Customer ID       1000 non-null   int64
 3   Product ID        1000 non-null   int64
 4   Size              965 non-null    str
 5   Color             467 non-null    str
 6   Unit Price        1000 non-null   float64
 7   Quantity          1000 non-null   int64
 8   Date              1000 non-null   str
 9   Discount          1000 non-null   float64
 10  Line Total        1000 non-null   float64
 11  Store ID          1000 non-null   int64
 12  Employee ID       1000 non-null   int64
 13  Currency          1000 non-null   str
 14  Currency Symbol   1000 non-null   str
 15  SKU               1000 non-null   str
 16  Transaction Type  1000 non-null   str
 17  Payment Method    1000 non-null   str
 18  Invoice Total     1000 non-null   float64
dtypes: float64(4), int64(6), str(9)
memory usage: 148.6 KB

### This code display the gender count for column gender in the customers dataset ###

In [42]:
customers["Gender"].value_counts(dropna=False)

Gender
M    964562
F    677041
D      1703
Name: count, dtype: int64

### This code display the category count for column category in the transactions preview dataset ###

In [43]:
products["Category"].value_counts(dropna=False)

Category
Feminine     7590
Masculine    6210
Children     4140
Name: count, dtype: int64

### This code display the transaction type count for column transaction type in the transaction preview dataset ###

In [44]:
transactions_preview["Transaction Type"].value_counts(dropna=False)

Transaction Type
Sale      944
Return     56
Name: count, dtype: int64

### This code display all sub category count for column sub category in the products dataset ###

In [45]:
products["Sub Category"].value_counts()

Sub Category
Accessories                             2070
Coats and Blazers                       1380
Pants and Jeans                         1380
Sportswear                              1380
Sweaters and Knitwear                    690
Dresses and Jumpsuits                    690
Shirts and Blouses                       690
T-shirts and Tops                        690
Skirts and Shorts                        690
Suits and Sets                           690
Lingerie and Pajamas                     690
Sweaters and Sweatshirts                 690
T-shirts and Polos                       690
Shirts                                   690
Suits and Blazers                        690
Underwear and Pajamas                    690
Baby (0-12 months)                       690
Girl and Boy (1-5 years, 6-14 years)     690
Coats                                    690
Sweaters                                 690
Pajamas                                  690
Name: count, dtype: int64

### This code display the first 10 row with gender, date of birth, city and country as selected column ###

In [46]:
customers[
    ["Gender", "Date Of Birth", "City", "Country"]
].head(10)

  Gender Date Of Birth      City        Country
0      M    2003-07-15  New York  United States
1      M    2000-06-16  New York  United States
2      F    2003-07-22  New York  United States
3      M    1996-11-12  New York  United States
4      F    1998-02-10  New York  United States
5      M    1988-01-06  New York  United States
6      M    2000-10-27  New York  United States
7      M    2007-03-03  New York  United States
8      M    1999-07-19  New York  United States
9      F    2003-03-03  New York  United States

### This code display number of unique customer id ###
### Notice that there are number of unique customer ids and customer row are the same. Hence there are no duplicated customer id since it is require for the to be unique ###

In [47]:
print("Customer rows:", len(customers))
print("Unique Customer IDs:", customers["Customer ID"].nunique())

Customer rows: 1643306
Unique Customer IDs: 1643306

## 1. Scenario

An online fashion retailer wants to investigate which customer demographic segments and product categories contribute to the highest product return rates. The dataset contains customer demographic information, product categories, and transaction records that distinguish between sales and returns, allowing return behaviour to be compared across different customer and product groups. The findings could help the retailer improve inventory planning and reduce costs associated with processing returned products.

## 2. Data Source

The dataset used for this analysis is the **Global Fashion Retail Stores Dataset** by Ric Gomes, obtained from Kaggle.

- customers.csv — customer demographic information
- products.csv — product and category information
- transactions.csv — sales and return transaction information

## 3. Raw Dataset Description

### customers.csv

The customers.csv dataset contains **1,643,306 rows and 9 columns**. Each row represents one customer.

The columns are:

- Customer ID — identifier used to distinguish each customer
- Name — customer name
- Email — customer email address
- Telephone — customer telephone number
- City — customer's city
- Country — customer's country
- Gender — customer's recorded gender category
- Date Of Birth — customer's date of birth
- Job Title — customer's recorded occupation or job title

For the business question, the most relevant demographic variables are Gender, Date Of Birth, City, and Country.

### products.csv

The products.csv dataset contains **17,940 rows and 12 columns**. Each row represents a product.

The columns include:

- Product ID — unique product identifier
- Category — main product category
- Sub Category — more detailed product classification
- Color — product colour
- Sizes — available product sizes
- Production Cost — cost associated with producing the product

The dataset contains three main product categories:

- Feminine — 7,590 products
- Masculine — 6,210 products
- Children — 4,140 products

Product ID will be used to connect the product information to transaction records.

### transactions.csv

The transactions.csv dataset contains transaction-level information. **1,000 rows and 19 columns** was initially loaded to inspect the dataset  without loading the entire large file into memory.

Each row represents a transaction line associated with a customer and a product.

Important columns include:

- Invoice ID — transaction invoice identifier
- Line — line number within an invoice
- Customer ID — identifies the customer involved in the transaction
- Product ID — identifies the product involved
- Size — size selected in the transaction
- Color — colour selected in the transaction
- Unit Price — price per unit
- Quantity — quantity involved in the transaction
- Date — date of the transaction
- Discount — discount applied
- Line Total — total for the transaction line
- Store ID — store associated with the transaction
- Employee ID — employee associated with the transaction
- Currency and Currency Symbol — transaction currency
- SKU — stock keeping unit
- Transaction Type — identifies whether the transaction is a Sale or Return
- Payment Method — method used for payment
- Invoice Total — total invoice amount

In the initial 1,000-row preview, there were **944 sales and 56 returns**.

## 4. Dataset Integration

The three datasets are related using two identifiers.

Customer ID connects the customer dataset to the transaction dataset:

**customers.csv → Customer ID → transactions.csv**

Product ID connects the transaction dataset to the product dataset:

**transactions.csv → Product ID → products.csv**

After integration, each transaction can be associated with both the demographic characteristics of the customer and the category of the purchased or returned product. This structure will allow return rates to be compared across demographic segments such as gender, age group, country, and city, as well as across product categories and sub-categories.